@startmindmap
 * Business Model
 ** Concept Design
 *** Ideation
 *** Concept Design
 *** Prototpying
 ** Detail Design
 *** Experimentating
 *** Detail Design
 ** Implementation
 *** Poiloting
 *** Lauch
 *** Reflection


@endmindmap