name: Practices CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploying to Github Pages
      uses: actions/setup-node@v3
    - run: git config --global user.email "ci@github.com"
    - run: git config --global user.name "ci"
    - run: npm install gh-pages
    - run: npm run build
    - run: npm run deploy
