name: Practices CI
permissions:
  contents: write
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        npm ci
        npm run build
    - name: Deploying to Github Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build
